DROP TABLE IF EXISTS order_details;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS baskets;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS userbasket;
DROP TABLE IF EXISTS total_basket;
