// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import ()

type Basket struct {
	BasketID    int64   `json:"basket_id"`
	BasketPrice float32 `json:"basket_price"`
	UserID      int64   `json:"user_id"`
}

type Order struct {
	OrderID   int64 `json:"order_id"`
	OrderDate int64 `json:"order_date"`
	BasketID  int64 `json:"basket_id"`
}

type OrderDetail struct {
	OrderDtsID int64 `json:"order_dts_id"`
	Quantity   int64 `json:"quantity"`
	ProductID  int64 `json:"product_id"`
	OrderID    int64 `json:"order_id"`
}

type Product struct {
	ProductID    int64   `json:"product_id"`
	ProductName  string  `json:"product_name"`
	ProductPrice float32 `json:"product_price"`
	ProductVat   int16   `json:"product_vat"`
}

type TotalBasket struct {
	Price      float32 `json:"price"`
	Vat        float32 `json:"vat"`
	TotalPrice float32 `json:"total_price"`
	Discount   float32 `json:"discount"`
}

type User struct {
	UserID            int64  `json:"user_id"`
	UserName          string `json:"user_name"`
	UserOrdersCount   int64  `json:"user_orders_count"`
	UserTotalPurchase string `json:"user_total_purchase"`
}

type Userbasket struct {
	ProductID    int64   `json:"product_id"`
	ProductName  string  `json:"product_name"`
	ProductPrice float32 `json:"product_price"`
	ProductVat   int16   `json:"product_vat"`
}
